id: app
title: Risk Management Steps
type: project
version: 0.0.0.2
icon: rmf_icon.png
introduction:
  format: markdown
  template: Risk Management Steps v0.0.0.1

catalog:
  category: Preview
  description:
    long: |
      Risk Management Steps
      ==================

      Edit this Markdown file to provide a long description of your compliance app. The contents of this file will be displayed in the GovReady-Q Compliance Apps Catalog.
    short: Risk Management Steps v0.0.0.1
  source_url: https://github.com/GovReady/apps
  status: stub
  vendor: none
  vendor_url: ~
  version: 0.0.0.2
questions:

#rmf
- id: rmf_step_1
  title: Step 1, Categorize Information Systems
  type: module
  icon: rmf_icon.png
  module-id: rmf_step_1
  group: Risk Management Framework Steps
- id: rmf_step_2
  title: Step 2, Select Security Controls
  type: module
  icon: rmf_icon.png
  module-id: rmf_step_2
  group: Risk Management Framework Steps
- id: rmf_step_3
  title: Step 3, Implement Security Controls
  type: module
  icon: rmf_icon.png
  module-id: rmf_step_3
  group: Risk Management Framework Steps
- id: rmf_step_4
  title: Step 4, Assess Security Controls
  type: module
  icon: rmf_icon.png
  module-id: rmf_step_4
  group: Risk Management Framework Steps
- id: rmf_step_5
  title: Step 5, Authorize Information System
  type: module
  icon: rmf_icon.png
  module-id: rmf_step_5
  group: Risk Management Framework Steps
- id: rmf_step_6
  title: Step 6, Monitor Security Controls
  type: module
  icon: rmf_icon.png
  module-id: rmf_step_6
  group: Risk Management Framework Steps

