id: app
title: Test App
type: project
version: 0.0.0.1
icon: rmf_icon.png
introduction:
  format: markdown
  template: Test App v0.0.0.1

catalog:
  category: Draft
  description:
    long: |
      Test App
      ==================
    short: Test App v0.0.0.1
  source_url: https://github.com/GovReady/apps
  status: stub
  vendor: none
  vendor_url: ~
  version: 0.0.0.1
questions:

#test app

- id: test_app
  title: Test App
  type: module
  icon: rmf_icon.png
  module-id: test_app
  group: Test apps

  



